# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client stub for the Synap service."""
import grpc
import warnings

from . import synap_service_pb2 as synap__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in synap_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SynapServiceStub(object):
    """Client stub for the Synap service."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Listen = channel.stream_stream(
                '/synap.v1.SynapService/Listen',
                request_serializer=synap__service__pb2.StreamEvent.SerializeToString,
                response_deserializer=synap__service__pb2.StreamResponse.FromString,
                _registered_method=True)
        self.IngestTelemetry = channel.stream_unary(
                '/synap.v1.SynapService/IngestTelemetry',
                request_serializer=synap__service__pb2.TelemetryEvent.SerializeToString,
                response_deserializer=synap__service__pb2.TelemetryAck.FromString,
                _registered_method=True)
